### ISSUE TITLE
Crash when entity gets destroyed

### ISSUE THREAD

**Issue by DarkShadow44** [Aurensar/factorio-factoryinspector#8]
I found a crash when exploding a nuke inside a base:

```
 142.150 Error MainLoop.cpp:1288: Exception at tick 1671345: The mod Factory Inspector (timspeedle crash fix fork) (1.1.17) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event timspeedle-fork-factory-inspector::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	...e-fork-factory-inspector__/script/production-tracker.lua:62: in function 'updateProductionAndConsumptionStatsFurnace'
	...eedle-fork-factory-inspector__/script/event-handlers.lua:46: in function <...eedle-fork-factory-inspector__/script/event-handlers.lua:15>
```

**Comment by jocker-il** [comment]
I've had the same issue, I suspect during an attack by biters that probably destroyed a furnace or assembler - I think you need a "entity destroyed" event handler to make sure to remove it from your array of inspected entities,

 the question is - is @Aurensar still working on this mod ? the last update was 9-10 months ago

**Comment by Aurensar** [comment]
I recently got back into Factorio, so I'll review open issues at the weekend and try to ship some fixes. Bear with me.

**Comment by Aurensar** [comment]
Should be resolved now. Please reopen if not fixed.

**Comment by Aurensar** [comment]
resolved
